---
title: "Monoprice Ultimate 3D Printer"
author: "David Gabbé"
date: "2/28/2020"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Monoprice Maker Ultimate 3D Printer MK11 DirectDrive Extruder / 24V Power System

Notes on setup/configuration for this Wanhao Duplicator 6 clone.

* Name: Monoprice Maker Ultimate 3D Printer, MK11 direct drive extruder / 24V power system.
* Rear tag: Monoprice Maker Select Pro Ultimate 3D Printer
* Part no: 15710
* Firmware: DEV 3.01

Status when unpacked:

* Machine on: 21:06
* Printing: 7:05
* Material: 12m

## Accessories

* [1mm feeler gauge](https://www.mcmaster.com/2283a26)
* [0.004" feeler gauge](https://www.mcmaster.com/20385a34)
* [0.015" dia High-Speed M2 Tool Steel Rod](https://www.mcmaster.com/3009a297) for unclogging nozzle. Will compare effectiveness to sewing needle.

## Filaments

See [filaments.md](./filaments.md) for settings and experience with different materials.

## Printer Settings & Tuning

_Likely to move to its own page_

The build leveling function does not offer a way to cancel out once started. There is no built-in feature to review the bed levelness.

This info is unvetted:

* https://www.youtube.com/watch?v=aYVuz9ccZL8

## Resources

* [Thingiverse collection](https://www.thingiverse.com/Printer3D_One/collections/wanhao-duplicator-6-d6-amp-monoprice-maker-ultimate-printed-parts-and-improvements) of various parts
* [Monoprice manual](https://downloads.monoprice.com/files/manuals/15710_Manual_160622.pdf)
* [Wanhao manual](http://www.wanhao3dprinter.com/xiazai/D6_User_Manual_REV_A.pdf). The Wanhao manual is easier to understand than the Monoprice one.

https://www.thingiverse.com/thing:42528

